# Generated by Django 4.2.11 on 2024-06-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sname", models.CharField(max_length=50)),
                ("sprincipal", models.CharField(max_length=50)),
                ("spno", models.CharField(max_length=50)),
                ("saddress", models.CharField(max_length=50)),
            ],
        ),
    ]
